import fields from './fields'

export const createFormData = () => ({
  showLabels: false,
  inputs: [
    {
      label: 'First Name',
      name: 'firstName',
      type: 'text',
      value: '',
      pattern: fields.oneWord.pattern,
      title: fields.oneWord.title('First Name'),
      icon: 'user',
      required: true,
    },
    {
      label: 'Last Name',
      name: 'lastName',
      type: 'text',
      value: '',
      pattern: fields.oneWord.pattern,
      title: fields.oneWord.title('Last Name'),
      icon: 'user',
      required: true,
    },
    {
      label: 'User Name',
      name: 'userName',
      type: 'text',
      value: '',
      pattern: fields.oneWord.pattern,
      title: fields.oneWord.title('User Name'),
      icon: 'user',
      required: true,
    },
    {
      label: 'Email',
      name: 'email',
      type: 'email',
      value: '',
      pattern: fields.email.pattern,
      title: fields.email.title,
      icon: 'email',
      required: true,
    },
    {
      label: 'Password',
      name: 'password',
      type: 'password',
      value: '',
      pattern: fields.password.pattern,
      title: fields.password.title,
      icon: 'password',
      required: true,
    },
  ],
  submitButtonText: 'Sign Up',
})
